<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Wallet extends Model
{
    use HasFactory;
    protected $fillable = [
        'balance',
        'pending',
        'card_number',
        'password',
        'type',
        'profile_id',
        'status'
    ];

    protected $hidden = ['password'];

    public function accountable()
    {
        return $this->morphTo();
    }

    // public static function boot()
    // {
    //     parent::boot(); // TODO: Change the autogenerated stub
    //     static::creating(function ($model) {
    //         $types = [
    //             'App\Models\Profile' => '82',
    //             'App\Models\Truck' => '83',
    //             'App\Models\Individual' => '84',
    //         ];
    //         $number = 222222222;
    //         $model->card_number = "4224" . $types[$model->accountable_type] . (str_pad((int)$model->accountable_id, 8, '3', STR_PAD_LEFT));
    //     });
    // }
}
